# Generated by Django 4.0.5 on 2022-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='code',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
    ]
