# Generated by Django 4.0.5 on 2022-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0002_plant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='age',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
