# Generated by Django 4.0.5 on 2022-06-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0008_plantimage_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='plant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plantImage', to='plant_app.plant'),
            preserve_default=False,
        ),
    ]
