# Generated by Django 4.0.5 on 2022-06-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0009_alter_plantimage_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
