# Generated by Django 4.0.5 on 2022-06-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0010_alter_plantimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.FileField(default='http://127.0.0.1:8000/media/images/default-plant.png', upload_to='images'),
        ),
    ]
