# Generated by Django 4.0.5 on 2022-06-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0013_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.FileField(blank=True, default='/images/default-plant.png', null=True, upload_to='images'),
        ),
    ]
