# Generated by Django 4.0.5 on 2022-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0014_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.FileField(default='/images/default-plant.png', upload_to='images'),
        ),
    ]
