# Generated by Django 4.0.5 on 2022-06-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0018_remove_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.FileField(default='/images/assets/default-plant.png', null=True, upload_to='images'),
        ),
    ]
