# Generated by Django 4.0.5 on 2022-06-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0019_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
